/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardWifiRouteImport } from './routes/_dashboard/wifi'
import { Route as DashboardSystemRouteImport } from './routes/_dashboard/system'
import { Route as DashboardDevicesRouteImport } from './routes/_dashboard/devices'
import { Route as DashboardCellRouteImport } from './routes/_dashboard/cell'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWifiRoute = DashboardWifiRouteImport.update({
  id: '/wifi',
  path: '/wifi',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSystemRoute = DashboardSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDevicesRoute = DashboardDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCellRoute = DashboardCellRouteImport.update({
  id: '/cell',
  path: '/cell',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/cell': typeof DashboardCellRoute
  '/devices': typeof DashboardDevicesRoute
  '/system': typeof DashboardSystemRoute
  '/wifi': typeof DashboardWifiRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/cell': typeof DashboardCellRoute
  '/devices': typeof DashboardDevicesRoute
  '/system': typeof DashboardSystemRoute
  '/wifi': typeof DashboardWifiRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/cell': typeof DashboardCellRoute
  '/_dashboard/devices': typeof DashboardDevicesRoute
  '/_dashboard/system': typeof DashboardSystemRoute
  '/_dashboard/wifi': typeof DashboardWifiRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/cell' | '/devices' | '/system' | '/wifi'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/cell' | '/devices' | '/system' | '/wifi' | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/cell'
    | '/_dashboard/devices'
    | '/_dashboard/system'
    | '/_dashboard/wifi'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/wifi': {
      id: '/_dashboard/wifi'
      path: '/wifi'
      fullPath: '/wifi'
      preLoaderRoute: typeof DashboardWifiRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/system': {
      id: '/_dashboard/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof DashboardSystemRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/devices': {
      id: '/_dashboard/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DashboardDevicesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/cell': {
      id: '/_dashboard/cell'
      path: '/cell'
      fullPath: '/cell'
      preLoaderRoute: typeof DashboardCellRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCellRoute: typeof DashboardCellRoute
  DashboardDevicesRoute: typeof DashboardDevicesRoute
  DashboardSystemRoute: typeof DashboardSystemRoute
  DashboardWifiRoute: typeof DashboardWifiRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCellRoute: DashboardCellRoute,
  DashboardDevicesRoute: DashboardDevicesRoute,
  DashboardSystemRoute: DashboardSystemRoute,
  DashboardWifiRoute: DashboardWifiRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
